### ISSUE TITLE
provid options for importing lists of computers to target

### ISSUE THREAD

**Issue by dstaulcu** [dstaulcu/PowerOps#8]
-from next file
-from manual entry
-from splunk query?
-from active directory query?
-from odbc  query?

**Comment by akahn16** [comment]
Can we write a module to support several of the import methods and write to a csv or array?

**Comment by dstaulcu** [comment]
Those features were added in last nights commit.  Try it!!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
